[package]
name = "rookie"
version = "0.3.6"
edition = "2021"
description = "Load cookie from your web browsers"
license-file = "MIT-LICENSE.txt"
homepage = "https://crates.io/crates/rookie"
documentation = "https://docs.rs/rookie/"
repository = "https://github.com/thewh1teagle/rookie"
readme = "../README.md"
keywords = ["windows", "cookies", "rust", "web"]

[lib]
name = "rookie"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "bin/main.rs"

[dependencies]
aes = "0.8.3"
aes-gcm = "0.10.3"
byteorder = "1.4.3"
cbc = "0.1.2"
cfg-if = "1.0.0"
glob = "0.3.1"
regex = "1.9.6"
rusqlite = { version = "0.29.0", features = ["bundled"] }
rust-ini = "0.19.0"
url = "2.4.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
zvariant = "3.15.0"
lz4_flex = "0.11.1"
log = "0.4.20"
anyhow = "1.0.75"


[target.'cfg(unix)'.dependencies]
sha1 = "0.10.6"
pbkdf2 = "0.12.2"

[target.'cfg(target_os = "linux")'.dependencies]
zbus = "3.14.1"

[target.'cfg(target_os = "macos")'.dependencies]
sha1 = "0.10.6"
pbkdf2 = "0.12.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.51.1", features = ["Win32_Security_Cryptography", "Win32_Foundation", "Win32_System", "Win32_System_RestartManager"] }
base64 = "0.21.4"
libesedb = "0.2.4"
